- name: Test Config
  hosts: localhost
  vars_files:
    - ./hello.{{ env }}.yml
  tasks:
    - name: Print from variable file
      debug:
        var: hello    
    - name: Print from GitHub variable
      debug:
        var: github_input